// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: proto2/scalars.proto

package proto2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumMessage_Num int32

const (
	EnumMessage_TEN   EnumMessage_Num = 10
	EnumMessage_NINE  EnumMessage_Num = 9
	EnumMessage_EIGHT EnumMessage_Num = 8
	EnumMessage_SEVEN EnumMessage_Num = 7
)

// Enum value maps for EnumMessage_Num.
var (
	EnumMessage_Num_name = map[int32]string{
		10: "TEN",
		9:  "NINE",
		8:  "EIGHT",
		7:  "SEVEN",
	}
	EnumMessage_Num_value = map[string]int32{
		"TEN":   10,
		"NINE":  9,
		"EIGHT": 8,
		"SEVEN": 7,
	}
)

func (x EnumMessage_Num) Enum() *EnumMessage_Num {
	p := new(EnumMessage_Num)
	*p = x
	return p
}

func (x EnumMessage_Num) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumMessage_Num) Descriptor() protoreflect.EnumDescriptor {
	return file_proto2_scalars_proto_enumTypes[0].Descriptor()
}

func (EnumMessage_Num) Type() protoreflect.EnumType {
	return &file_proto2_scalars_proto_enumTypes[0]
}

func (x EnumMessage_Num) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumMessage_Num) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumMessage_Num(num)
	return nil
}

// Deprecated: Use EnumMessage_Num.Descriptor instead.
func (EnumMessage_Num) EnumDescriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{15, 0}
}

type DoubleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *float64  `protobuf:"fixed64,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *float64  `protobuf:"fixed64,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []float64 `protobuf:"fixed64,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []float64 `protobuf:"fixed64,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for DoubleMessage fields.
const (
	Default_DoubleMessage_RequiredField = float64(1)
	Default_DoubleMessage_OptionalField = float64(2)
)

func (x *DoubleMessage) Reset() {
	*x = DoubleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleMessage) ProtoMessage() {}

func (x *DoubleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleMessage.ProtoReflect.Descriptor instead.
func (*DoubleMessage) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{0}
}

func (x *DoubleMessage) GetRequiredField() float64 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_DoubleMessage_RequiredField
}

func (x *DoubleMessage) GetOptionalField() float64 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_DoubleMessage_OptionalField
}

func (x *DoubleMessage) GetRepeatedField() []float64 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *DoubleMessage) GetPackedField() []float64 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type FloatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *float32  `protobuf:"fixed32,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *float32  `protobuf:"fixed32,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []float32 `protobuf:"fixed32,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []float32 `protobuf:"fixed32,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for FloatMessage fields.
const (
	Default_FloatMessage_RequiredField = float32(1)
	Default_FloatMessage_OptionalField = float32(2)
)

func (x *FloatMessage) Reset() {
	*x = FloatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatMessage) ProtoMessage() {}

func (x *FloatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatMessage.ProtoReflect.Descriptor instead.
func (*FloatMessage) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{1}
}

func (x *FloatMessage) GetRequiredField() float32 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_FloatMessage_RequiredField
}

func (x *FloatMessage) GetOptionalField() float32 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_FloatMessage_OptionalField
}

func (x *FloatMessage) GetRepeatedField() []float32 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *FloatMessage) GetPackedField() []float32 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type Int32Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *int32  `protobuf:"varint,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *int32  `protobuf:"varint,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []int32 `protobuf:"varint,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []int32 `protobuf:"varint,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for Int32Message fields.
const (
	Default_Int32Message_RequiredField = int32(1)
	Default_Int32Message_OptionalField = int32(2)
)

func (x *Int32Message) Reset() {
	*x = Int32Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Message) ProtoMessage() {}

func (x *Int32Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Message.ProtoReflect.Descriptor instead.
func (*Int32Message) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{2}
}

func (x *Int32Message) GetRequiredField() int32 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_Int32Message_RequiredField
}

func (x *Int32Message) GetOptionalField() int32 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_Int32Message_OptionalField
}

func (x *Int32Message) GetRepeatedField() []int32 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *Int32Message) GetPackedField() []int32 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type Int64Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *int64  `protobuf:"varint,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *int64  `protobuf:"varint,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []int64 `protobuf:"varint,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []int64 `protobuf:"varint,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for Int64Message fields.
const (
	Default_Int64Message_RequiredField = int64(1)
	Default_Int64Message_OptionalField = int64(2)
)

func (x *Int64Message) Reset() {
	*x = Int64Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int64Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64Message) ProtoMessage() {}

func (x *Int64Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64Message.ProtoReflect.Descriptor instead.
func (*Int64Message) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{3}
}

func (x *Int64Message) GetRequiredField() int64 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_Int64Message_RequiredField
}

func (x *Int64Message) GetOptionalField() int64 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_Int64Message_OptionalField
}

func (x *Int64Message) GetRepeatedField() []int64 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *Int64Message) GetPackedField() []int64 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type Uint32Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *uint32  `protobuf:"varint,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *uint32  `protobuf:"varint,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []uint32 `protobuf:"varint,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []uint32 `protobuf:"varint,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for Uint32Message fields.
const (
	Default_Uint32Message_RequiredField = uint32(1)
	Default_Uint32Message_OptionalField = uint32(2)
)

func (x *Uint32Message) Reset() {
	*x = Uint32Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint32Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32Message) ProtoMessage() {}

func (x *Uint32Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32Message.ProtoReflect.Descriptor instead.
func (*Uint32Message) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{4}
}

func (x *Uint32Message) GetRequiredField() uint32 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_Uint32Message_RequiredField
}

func (x *Uint32Message) GetOptionalField() uint32 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_Uint32Message_OptionalField
}

func (x *Uint32Message) GetRepeatedField() []uint32 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *Uint32Message) GetPackedField() []uint32 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type Uint64Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *uint64  `protobuf:"varint,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *uint64  `protobuf:"varint,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []uint64 `protobuf:"varint,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []uint64 `protobuf:"varint,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for Uint64Message fields.
const (
	Default_Uint64Message_RequiredField = uint64(1)
	Default_Uint64Message_OptionalField = uint64(2)
)

func (x *Uint64Message) Reset() {
	*x = Uint64Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint64Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64Message) ProtoMessage() {}

func (x *Uint64Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64Message.ProtoReflect.Descriptor instead.
func (*Uint64Message) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{5}
}

func (x *Uint64Message) GetRequiredField() uint64 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_Uint64Message_RequiredField
}

func (x *Uint64Message) GetOptionalField() uint64 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_Uint64Message_OptionalField
}

func (x *Uint64Message) GetRepeatedField() []uint64 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *Uint64Message) GetPackedField() []uint64 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type Sint32Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *int32  `protobuf:"zigzag32,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *int32  `protobuf:"zigzag32,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []int32 `protobuf:"zigzag32,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []int32 `protobuf:"zigzag32,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for Sint32Message fields.
const (
	Default_Sint32Message_RequiredField = int32(1)
	Default_Sint32Message_OptionalField = int32(2)
)

func (x *Sint32Message) Reset() {
	*x = Sint32Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sint32Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sint32Message) ProtoMessage() {}

func (x *Sint32Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sint32Message.ProtoReflect.Descriptor instead.
func (*Sint32Message) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{6}
}

func (x *Sint32Message) GetRequiredField() int32 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_Sint32Message_RequiredField
}

func (x *Sint32Message) GetOptionalField() int32 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_Sint32Message_OptionalField
}

func (x *Sint32Message) GetRepeatedField() []int32 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *Sint32Message) GetPackedField() []int32 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type Sint64Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *int64  `protobuf:"zigzag64,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *int64  `protobuf:"zigzag64,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []int64 `protobuf:"zigzag64,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []int64 `protobuf:"zigzag64,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for Sint64Message fields.
const (
	Default_Sint64Message_RequiredField = int64(1)
	Default_Sint64Message_OptionalField = int64(2)
)

func (x *Sint64Message) Reset() {
	*x = Sint64Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sint64Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sint64Message) ProtoMessage() {}

func (x *Sint64Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sint64Message.ProtoReflect.Descriptor instead.
func (*Sint64Message) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{7}
}

func (x *Sint64Message) GetRequiredField() int64 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_Sint64Message_RequiredField
}

func (x *Sint64Message) GetOptionalField() int64 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_Sint64Message_OptionalField
}

func (x *Sint64Message) GetRepeatedField() []int64 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *Sint64Message) GetPackedField() []int64 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type Fixed32Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *uint32  `protobuf:"fixed32,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *uint32  `protobuf:"fixed32,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []uint32 `protobuf:"fixed32,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []uint32 `protobuf:"fixed32,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for Fixed32Message fields.
const (
	Default_Fixed32Message_RequiredField = uint32(1)
	Default_Fixed32Message_OptionalField = uint32(2)
)

func (x *Fixed32Message) Reset() {
	*x = Fixed32Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fixed32Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fixed32Message) ProtoMessage() {}

func (x *Fixed32Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fixed32Message.ProtoReflect.Descriptor instead.
func (*Fixed32Message) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{8}
}

func (x *Fixed32Message) GetRequiredField() uint32 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_Fixed32Message_RequiredField
}

func (x *Fixed32Message) GetOptionalField() uint32 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_Fixed32Message_OptionalField
}

func (x *Fixed32Message) GetRepeatedField() []uint32 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *Fixed32Message) GetPackedField() []uint32 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type Fixed64Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *uint64  `protobuf:"fixed64,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *uint64  `protobuf:"fixed64,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []uint64 `protobuf:"fixed64,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []uint64 `protobuf:"fixed64,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for Fixed64Message fields.
const (
	Default_Fixed64Message_RequiredField = uint64(1)
	Default_Fixed64Message_OptionalField = uint64(2)
)

func (x *Fixed64Message) Reset() {
	*x = Fixed64Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fixed64Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fixed64Message) ProtoMessage() {}

func (x *Fixed64Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fixed64Message.ProtoReflect.Descriptor instead.
func (*Fixed64Message) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{9}
}

func (x *Fixed64Message) GetRequiredField() uint64 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_Fixed64Message_RequiredField
}

func (x *Fixed64Message) GetOptionalField() uint64 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_Fixed64Message_OptionalField
}

func (x *Fixed64Message) GetRepeatedField() []uint64 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *Fixed64Message) GetPackedField() []uint64 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type Sfixed32Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *int32  `protobuf:"fixed32,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *int32  `protobuf:"fixed32,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []int32 `protobuf:"fixed32,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []int32 `protobuf:"fixed32,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for Sfixed32Message fields.
const (
	Default_Sfixed32Message_RequiredField = int32(1)
	Default_Sfixed32Message_OptionalField = int32(2)
)

func (x *Sfixed32Message) Reset() {
	*x = Sfixed32Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sfixed32Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sfixed32Message) ProtoMessage() {}

func (x *Sfixed32Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sfixed32Message.ProtoReflect.Descriptor instead.
func (*Sfixed32Message) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{10}
}

func (x *Sfixed32Message) GetRequiredField() int32 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_Sfixed32Message_RequiredField
}

func (x *Sfixed32Message) GetOptionalField() int32 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_Sfixed32Message_OptionalField
}

func (x *Sfixed32Message) GetRepeatedField() []int32 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *Sfixed32Message) GetPackedField() []int32 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type Sfixed64Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *int64  `protobuf:"fixed64,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *int64  `protobuf:"fixed64,2,opt,name=optional_field,json=optionalField,def=2" json:"optional_field,omitempty"`
	RepeatedField []int64 `protobuf:"fixed64,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []int64 `protobuf:"fixed64,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for Sfixed64Message fields.
const (
	Default_Sfixed64Message_RequiredField = int64(1)
	Default_Sfixed64Message_OptionalField = int64(2)
)

func (x *Sfixed64Message) Reset() {
	*x = Sfixed64Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sfixed64Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sfixed64Message) ProtoMessage() {}

func (x *Sfixed64Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sfixed64Message.ProtoReflect.Descriptor instead.
func (*Sfixed64Message) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{11}
}

func (x *Sfixed64Message) GetRequiredField() int64 {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_Sfixed64Message_RequiredField
}

func (x *Sfixed64Message) GetOptionalField() int64 {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_Sfixed64Message_OptionalField
}

func (x *Sfixed64Message) GetRepeatedField() []int64 {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *Sfixed64Message) GetPackedField() []int64 {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type BoolMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *bool  `protobuf:"varint,1,req,name=required_field,json=requiredField,def=1" json:"required_field,omitempty"`
	OptionalField *bool  `protobuf:"varint,2,opt,name=optional_field,json=optionalField" json:"optional_field,omitempty"`
	RepeatedField []bool `protobuf:"varint,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
	PackedField   []bool `protobuf:"varint,4,rep,packed,name=packed_field,json=packedField" json:"packed_field,omitempty"`
}

// Default values for BoolMessage fields.
const (
	Default_BoolMessage_RequiredField = bool(true)
)

func (x *BoolMessage) Reset() {
	*x = BoolMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolMessage) ProtoMessage() {}

func (x *BoolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolMessage.ProtoReflect.Descriptor instead.
func (*BoolMessage) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{12}
}

func (x *BoolMessage) GetRequiredField() bool {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_BoolMessage_RequiredField
}

func (x *BoolMessage) GetOptionalField() bool {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return false
}

func (x *BoolMessage) GetRepeatedField() []bool {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *BoolMessage) GetPackedField() []bool {
	if x != nil {
		return x.PackedField
	}
	return nil
}

type StringMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *string  `protobuf:"bytes,1,req,name=required_field,json=requiredField,def=req" json:"required_field,omitempty"`
	OptionalField *string  `protobuf:"bytes,2,opt,name=optional_field,json=optionalField,def=opt" json:"optional_field,omitempty"`
	RepeatedField []string `protobuf:"bytes,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
}

// Default values for StringMessage fields.
const (
	Default_StringMessage_RequiredField = string("req")
	Default_StringMessage_OptionalField = string("opt")
)

func (x *StringMessage) Reset() {
	*x = StringMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMessage) ProtoMessage() {}

func (x *StringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMessage.ProtoReflect.Descriptor instead.
func (*StringMessage) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{13}
}

func (x *StringMessage) GetRequiredField() string {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_StringMessage_RequiredField
}

func (x *StringMessage) GetOptionalField() string {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return Default_StringMessage_OptionalField
}

func (x *StringMessage) GetRepeatedField() []string {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

type BytesMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField []byte   `protobuf:"bytes,1,req,name=required_field,json=requiredField,def=req" json:"required_field,omitempty"`
	OptionalField []byte   `protobuf:"bytes,2,opt,name=optional_field,json=optionalField,def=opt" json:"optional_field,omitempty"`
	RepeatedField [][]byte `protobuf:"bytes,3,rep,name=repeated_field,json=repeatedField" json:"repeated_field,omitempty"`
}

// Default values for BytesMessage fields.
var (
	Default_BytesMessage_RequiredField = []byte("req")
	Default_BytesMessage_OptionalField = []byte("opt")
)

func (x *BytesMessage) Reset() {
	*x = BytesMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesMessage) ProtoMessage() {}

func (x *BytesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesMessage.ProtoReflect.Descriptor instead.
func (*BytesMessage) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{14}
}

func (x *BytesMessage) GetRequiredField() []byte {
	if x != nil && x.RequiredField != nil {
		return x.RequiredField
	}
	return append([]byte(nil), Default_BytesMessage_RequiredField...)
}

func (x *BytesMessage) GetOptionalField() []byte {
	if x != nil && x.OptionalField != nil {
		return x.OptionalField
	}
	return append([]byte(nil), Default_BytesMessage_OptionalField...)
}

func (x *BytesMessage) GetRepeatedField() [][]byte {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

type EnumMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequiredField *EnumMessage_Num  `protobuf:"varint,1,req,name=required_field,json=requiredField,enum=EnumMessage_Num,def=7" json:"required_field,omitempty"`
	OptionalField *EnumMessage_Num  `protobuf:"varint,2,opt,name=optional_field,json=optionalField,enum=EnumMessage_Num" json:"optional_field,omitempty"`
	RepeatedField []EnumMessage_Num `protobuf:"varint,3,rep,name=repeated_field,json=repeatedField,enum=EnumMessage_Num" json:"repeated_field,omitempty"`
	PackedField   []EnumMessage_Num `protobuf:"varint,4,rep,packed,name=packed_field,json=packedField,enum=EnumMessage_Num" json:"packed_field,omitempty"`
}

// Default values for EnumMessage fields.
const (
	Default_EnumMessage_RequiredField = EnumMessage_SEVEN
)

func (x *EnumMessage) Reset() {
	*x = EnumMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto2_scalars_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumMessage) ProtoMessage() {}

func (x *EnumMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto2_scalars_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumMessage.ProtoReflect.Descriptor instead.
func (*EnumMessage) Descriptor() ([]byte, []int) {
	return file_proto2_scalars_proto_rawDescGZIP(), []int{15}
}

func (x *EnumMessage) GetRequiredField() EnumMessage_Num {
	if x != nil && x.RequiredField != nil {
		return *x.RequiredField
	}
	return Default_EnumMessage_RequiredField
}

func (x *EnumMessage) GetOptionalField() EnumMessage_Num {
	if x != nil && x.OptionalField != nil {
		return *x.OptionalField
	}
	return EnumMessage_TEN
}

func (x *EnumMessage) GetRepeatedField() []EnumMessage_Num {
	if x != nil {
		return x.RepeatedField
	}
	return nil
}

func (x *EnumMessage) GetPackedField() []EnumMessage_Num {
	if x != nil {
		return x.PackedField
	}
	return nil
}

var File_proto2_scalars_proto protoreflect.FileDescriptor

var file_proto2_scalars_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x2f, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x0d, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x01,
	0x3a, 0x01, 0x31, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x28, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x3a, 0x01, 0x32, 0x52, 0x0d, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e,
	0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0b, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xb0, 0x01, 0x0a, 0x0c, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0e, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x02, 0x3a, 0x01, 0x31, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x28, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x3a, 0x01, 0x32,
	0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x02, 0x42, 0x02, 0x10, 0x01,
	0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xb0, 0x01,
	0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28,
	0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x3a, 0x01, 0x31, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x28, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x3a, 0x01, 0x32, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0c, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x42,
	0x02, 0x10, 0x01, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x22, 0xb0, 0x01, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x28, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x3a, 0x01, 0x31, 0x52, 0x0d, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x28, 0x0a, 0x0e, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x3a, 0x01, 0x32, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0d, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0c,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x03, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x0d, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x3a, 0x01, 0x31,
	0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x28, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x32, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x25, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x0d, 0x55, 0x69, 0x6e, 0x74,
	0x36, 0x34, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0e, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x04, 0x3a, 0x01, 0x31, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x28, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x3a, 0x01, 0x32, 0x52, 0x0d,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x04, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0b,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x0d,
	0x53, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a,
	0x0e, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x11, 0x3a, 0x01, 0x31, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x28, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x3a,
	0x01, 0x32, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x11, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x11, 0x42, 0x02,
	0x10, 0x01, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22,
	0xb1, 0x01, 0x0a, 0x0d, 0x53, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x28, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x12, 0x3a, 0x01, 0x31, 0x52, 0x0d, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x28, 0x0a, 0x0e, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x12, 0x3a, 0x01, 0x32, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x12, 0x52, 0x0d, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0c,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x12, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x22, 0xb2, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x07, 0x3a, 0x01,
	0x31, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x28, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x3a, 0x01, 0x32, 0x52, 0x0d, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x07, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x25, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x07, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0b, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xb2, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x78,
	0x65, 0x64, 0x36, 0x34, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0e, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x06, 0x3a, 0x01, 0x31, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x28, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06, 0x3a, 0x01, 0x32,
	0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x06, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x06, 0x42, 0x02, 0x10, 0x01,
	0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xb3, 0x01,
	0x0a, 0x0f, 0x53, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x28, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0f, 0x3a, 0x01, 0x31, 0x52, 0x0d, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x28, 0x0a, 0x0e, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0f, 0x3a, 0x01, 0x32, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0f, 0x52, 0x0d, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0c,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0f, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x22, 0xb3, 0x01, 0x0a, 0x0f, 0x53, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x10, 0x3a,
	0x01, 0x31, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x28, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x10, 0x3a, 0x01, 0x32, 0x52, 0x0d, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x10, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x10, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0b, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xaf, 0x01, 0x0a, 0x0b, 0x42, 0x6f,
	0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x0e, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x08, 0x3a, 0x04, 0x74, 0x72, 0x75, 0x65, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x08, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x08, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0b,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x8e, 0x01, 0x0a, 0x0d,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a,
	0x0e, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x09, 0x3a, 0x03, 0x72, 0x65, 0x71, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2a, 0x0a, 0x0e, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x3a, 0x03, 0x6f, 0x70, 0x74, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x8d, 0x01, 0x0a,
	0x0c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a,
	0x0e, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0c, 0x3a, 0x03, 0x72, 0x65, 0x71, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2a, 0x0a, 0x0e, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x3a, 0x03, 0x6f, 0x70, 0x74, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0d, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0xa8, 0x02, 0x0a,
	0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3e, 0x0a, 0x0e,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x3a, 0x05, 0x53, 0x45, 0x56, 0x45, 0x4e, 0x52, 0x0d, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x37, 0x0a, 0x0e,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x52, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x37, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x52,
	0x0d, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x37,
	0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x2e, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x12, 0x07,
	0x0a, 0x03, 0x54, 0x45, 0x4e, 0x10, 0x0a, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x49, 0x4e, 0x45, 0x10,
	0x09, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x49, 0x47, 0x48, 0x54, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x45, 0x56, 0x45, 0x4e, 0x10, 0x07, 0x42, 0x12, 0x5a, 0x10, 0x74, 0x65, 0x73, 0x74, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32,
}

var (
	file_proto2_scalars_proto_rawDescOnce sync.Once
	file_proto2_scalars_proto_rawDescData = file_proto2_scalars_proto_rawDesc
)

func file_proto2_scalars_proto_rawDescGZIP() []byte {
	file_proto2_scalars_proto_rawDescOnce.Do(func() {
		file_proto2_scalars_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto2_scalars_proto_rawDescData)
	})
	return file_proto2_scalars_proto_rawDescData
}

var file_proto2_scalars_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto2_scalars_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto2_scalars_proto_goTypes = []interface{}{
	(EnumMessage_Num)(0),    // 0: EnumMessage.Num
	(*DoubleMessage)(nil),   // 1: DoubleMessage
	(*FloatMessage)(nil),    // 2: FloatMessage
	(*Int32Message)(nil),    // 3: Int32Message
	(*Int64Message)(nil),    // 4: Int64Message
	(*Uint32Message)(nil),   // 5: Uint32Message
	(*Uint64Message)(nil),   // 6: Uint64Message
	(*Sint32Message)(nil),   // 7: Sint32Message
	(*Sint64Message)(nil),   // 8: Sint64Message
	(*Fixed32Message)(nil),  // 9: Fixed32Message
	(*Fixed64Message)(nil),  // 10: Fixed64Message
	(*Sfixed32Message)(nil), // 11: Sfixed32Message
	(*Sfixed64Message)(nil), // 12: Sfixed64Message
	(*BoolMessage)(nil),     // 13: BoolMessage
	(*StringMessage)(nil),   // 14: StringMessage
	(*BytesMessage)(nil),    // 15: BytesMessage
	(*EnumMessage)(nil),     // 16: EnumMessage
}
var file_proto2_scalars_proto_depIdxs = []int32{
	0, // 0: EnumMessage.required_field:type_name -> EnumMessage.Num
	0, // 1: EnumMessage.optional_field:type_name -> EnumMessage.Num
	0, // 2: EnumMessage.repeated_field:type_name -> EnumMessage.Num
	0, // 3: EnumMessage.packed_field:type_name -> EnumMessage.Num
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto2_scalars_proto_init() }
func file_proto2_scalars_proto_init() {
	if File_proto2_scalars_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto2_scalars_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int32Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int64Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uint32Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uint64Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sint32Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sint64Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fixed32Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fixed64Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sfixed32Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sfixed64Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto2_scalars_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto2_scalars_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto2_scalars_proto_goTypes,
		DependencyIndexes: file_proto2_scalars_proto_depIdxs,
		EnumInfos:         file_proto2_scalars_proto_enumTypes,
		MessageInfos:      file_proto2_scalars_proto_msgTypes,
	}.Build()
	File_proto2_scalars_proto = out.File
	file_proto2_scalars_proto_rawDesc = nil
	file_proto2_scalars_proto_goTypes = nil
	file_proto2_scalars_proto_depIdxs = nil
}
