// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: unique/unique.proto

package unique

import (
	_ "github.com/planetscale/vtprotobuf/vtproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UniqueFieldExtension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foo           string                 `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar           map[string]int64       `protobuf:"bytes,2,rep,name=bar,proto3" json:"bar,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Baz           map[int64]string       `protobuf:"bytes,3,rep,name=baz,proto3" json:"baz,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueFieldExtension) Reset() {
	*x = UniqueFieldExtension{}
	mi := &file_unique_unique_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueFieldExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueFieldExtension) ProtoMessage() {}

func (x *UniqueFieldExtension) ProtoReflect() protoreflect.Message {
	mi := &file_unique_unique_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueFieldExtension.ProtoReflect.Descriptor instead.
func (*UniqueFieldExtension) Descriptor() ([]byte, []int) {
	return file_unique_unique_proto_rawDescGZIP(), []int{0}
}

func (x *UniqueFieldExtension) GetFoo() string {
	if x != nil {
		return x.Foo
	}
	return ""
}

func (x *UniqueFieldExtension) GetBar() map[string]int64 {
	if x != nil {
		return x.Bar
	}
	return nil
}

func (x *UniqueFieldExtension) GetBaz() map[int64]string {
	if x != nil {
		return x.Baz
	}
	return nil
}

var File_unique_unique_proto protoreflect.FileDescriptor

const file_unique_unique_proto_rawDesc = "" +
	"\n" +
	"\x13unique/unique.proto\x1a3github.com/planetscale/vtprotobuf/vtproto/ext.proto\"\x94\x02\n" +
	"\x14UniqueFieldExtension\x12\x18\n" +
	"\x03foo\x18\x01 \x01(\tB\x06\xb2\xa9\x1f\x02\b\x01R\x03foo\x128\n" +
	"\x03bar\x18\x02 \x03(\v2\x1e.UniqueFieldExtension.BarEntryB\x06\xb2\xa9\x1f\x02\b\x01R\x03bar\x128\n" +
	"\x03baz\x18\x03 \x03(\v2\x1e.UniqueFieldExtension.BazEntryB\x06\xb2\xa9\x1f\x02\b\x01R\x03baz\x1a6\n" +
	"\bBarEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a6\n" +
	"\bBazEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12Z\x10testproto/uniqueb\x06proto3"

var (
	file_unique_unique_proto_rawDescOnce sync.Once
	file_unique_unique_proto_rawDescData []byte
)

func file_unique_unique_proto_rawDescGZIP() []byte {
	file_unique_unique_proto_rawDescOnce.Do(func() {
		file_unique_unique_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_unique_unique_proto_rawDesc), len(file_unique_unique_proto_rawDesc)))
	})
	return file_unique_unique_proto_rawDescData
}

var file_unique_unique_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_unique_unique_proto_goTypes = []any{
	(*UniqueFieldExtension)(nil), // 0: UniqueFieldExtension
	nil,                          // 1: UniqueFieldExtension.BarEntry
	nil,                          // 2: UniqueFieldExtension.BazEntry
}
var file_unique_unique_proto_depIdxs = []int32{
	1, // 0: UniqueFieldExtension.bar:type_name -> UniqueFieldExtension.BarEntry
	2, // 1: UniqueFieldExtension.baz:type_name -> UniqueFieldExtension.BazEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_unique_unique_proto_init() }
func file_unique_unique_proto_init() {
	if File_unique_unique_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_unique_unique_proto_rawDesc), len(file_unique_unique_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unique_unique_proto_goTypes,
		DependencyIndexes: file_unique_unique_proto_depIdxs,
		MessageInfos:      file_unique_unique_proto_msgTypes,
	}.Build()
	File_unique_unique_proto = out.File
	file_unique_unique_proto_goTypes = nil
	file_unique_unique_proto_depIdxs = nil
}
