// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: pool/pool_with_oneof.proto

package pool

import (
	_ "github.com/planetscale/vtprotobuf/vtproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneofTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Test:
	//
	//	*OneofTest_Test1_
	//	*OneofTest_Test2_
	//	*OneofTest_Test3_
	Test isOneofTest_Test `protobuf_oneof:"test"`
}

func (x *OneofTest) Reset() {
	*x = OneofTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pool_pool_with_oneof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneofTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofTest) ProtoMessage() {}

func (x *OneofTest) ProtoReflect() protoreflect.Message {
	mi := &file_pool_pool_with_oneof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofTest.ProtoReflect.Descriptor instead.
func (*OneofTest) Descriptor() ([]byte, []int) {
	return file_pool_pool_with_oneof_proto_rawDescGZIP(), []int{0}
}

func (m *OneofTest) GetTest() isOneofTest_Test {
	if m != nil {
		return m.Test
	}
	return nil
}

func (x *OneofTest) GetTest1() *OneofTest_Test1 {
	if x, ok := x.GetTest().(*OneofTest_Test1_); ok {
		return x.Test1
	}
	return nil
}

func (x *OneofTest) GetTest2() *OneofTest_Test2 {
	if x, ok := x.GetTest().(*OneofTest_Test2_); ok {
		return x.Test2
	}
	return nil
}

func (x *OneofTest) GetTest3() *OneofTest_Test3 {
	if x, ok := x.GetTest().(*OneofTest_Test3_); ok {
		return x.Test3
	}
	return nil
}

type isOneofTest_Test interface {
	isOneofTest_Test()
}

type OneofTest_Test1_ struct {
	Test1 *OneofTest_Test1 `protobuf:"bytes,1,opt,name=test1,proto3,oneof"`
}

type OneofTest_Test2_ struct {
	Test2 *OneofTest_Test2 `protobuf:"bytes,2,opt,name=test2,proto3,oneof"`
}

type OneofTest_Test3_ struct {
	Test3 *OneofTest_Test3 `protobuf:"bytes,3,opt,name=test3,proto3,oneof"`
}

func (*OneofTest_Test1_) isOneofTest_Test() {}

func (*OneofTest_Test2_) isOneofTest_Test() {}

func (*OneofTest_Test3_) isOneofTest_Test() {}

type OneofTest_Test1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int64 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *OneofTest_Test1) Reset() {
	*x = OneofTest_Test1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pool_pool_with_oneof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneofTest_Test1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofTest_Test1) ProtoMessage() {}

func (x *OneofTest_Test1) ProtoReflect() protoreflect.Message {
	mi := &file_pool_pool_with_oneof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofTest_Test1.ProtoReflect.Descriptor instead.
func (*OneofTest_Test1) Descriptor() ([]byte, []int) {
	return file_pool_pool_with_oneof_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OneofTest_Test1) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

type OneofTest_Test2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B []string `protobuf:"bytes,1,rep,name=b,proto3" json:"b,omitempty"`
}

func (x *OneofTest_Test2) Reset() {
	*x = OneofTest_Test2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pool_pool_with_oneof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneofTest_Test2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofTest_Test2) ProtoMessage() {}

func (x *OneofTest_Test2) ProtoReflect() protoreflect.Message {
	mi := &file_pool_pool_with_oneof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofTest_Test2.ProtoReflect.Descriptor instead.
func (*OneofTest_Test2) Descriptor() ([]byte, []int) {
	return file_pool_pool_with_oneof_proto_rawDescGZIP(), []int{0, 1}
}

func (x *OneofTest_Test2) GetB() []string {
	if x != nil {
		return x.B
	}
	return nil
}

type OneofTest_Test3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C *OneofTest_Test3_Element2 `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
}

func (x *OneofTest_Test3) Reset() {
	*x = OneofTest_Test3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pool_pool_with_oneof_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneofTest_Test3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofTest_Test3) ProtoMessage() {}

func (x *OneofTest_Test3) ProtoReflect() protoreflect.Message {
	mi := &file_pool_pool_with_oneof_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofTest_Test3.ProtoReflect.Descriptor instead.
func (*OneofTest_Test3) Descriptor() ([]byte, []int) {
	return file_pool_pool_with_oneof_proto_rawDescGZIP(), []int{0, 2}
}

func (x *OneofTest_Test3) GetC() *OneofTest_Test3_Element2 {
	if x != nil {
		return x.C
	}
	return nil
}

type OneofTest_Test3_Element2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	D int64 `protobuf:"varint,1,opt,name=d,proto3" json:"d,omitempty"`
}

func (x *OneofTest_Test3_Element2) Reset() {
	*x = OneofTest_Test3_Element2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pool_pool_with_oneof_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneofTest_Test3_Element2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofTest_Test3_Element2) ProtoMessage() {}

func (x *OneofTest_Test3_Element2) ProtoReflect() protoreflect.Message {
	mi := &file_pool_pool_with_oneof_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofTest_Test3_Element2.ProtoReflect.Descriptor instead.
func (*OneofTest_Test3_Element2) Descriptor() ([]byte, []int) {
	return file_pool_pool_with_oneof_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *OneofTest_Test3_Element2) GetD() int64 {
	if x != nil {
		return x.D
	}
	return 0
}

var File_pool_pool_with_oneof_proto protoreflect.FileDescriptor

var file_pool_pool_with_oneof_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6f, 0x6f, 0x6c, 0x2f, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x77, 0x69, 0x74, 0x68,
	0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x33, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x2f, 0x76, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x76, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa9, 0x02, 0x0a, 0x09, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x54, 0x65, 0x73, 0x74, 0x12,
	0x28, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x54, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x31,
	0x48, 0x00, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x31, 0x12, 0x28, 0x0a, 0x05, 0x74, 0x65, 0x73,
	0x74, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4f, 0x6e, 0x65, 0x6f, 0x66,
	0x54, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x32, 0x48, 0x00, 0x52, 0x05, 0x74, 0x65,
	0x73, 0x74, 0x32, 0x12, 0x28, 0x0a, 0x05, 0x74, 0x65, 0x73, 0x74, 0x33, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x54, 0x65, 0x73, 0x74, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x33, 0x48, 0x00, 0x52, 0x05, 0x74, 0x65, 0x73, 0x74, 0x33, 0x1a, 0x1b, 0x0a,
	0x05, 0x54, 0x65, 0x73, 0x74, 0x31, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x01, 0x61, 0x3a, 0x04, 0xa8, 0xa6, 0x1f, 0x01, 0x1a, 0x1b, 0x0a, 0x05, 0x54, 0x65,
	0x73, 0x74, 0x32, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x01,
	0x62, 0x3a, 0x04, 0xa8, 0xa6, 0x1f, 0x01, 0x1a, 0x56, 0x0a, 0x05, 0x54, 0x65, 0x73, 0x74, 0x33,
	0x12, 0x27, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x4f, 0x6e,
	0x65, 0x6f, 0x66, 0x54, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x33, 0x2e, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x52, 0x01, 0x63, 0x1a, 0x1e, 0x0a, 0x08, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x32, 0x12, 0x0c, 0x0a, 0x01, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x01, 0x64, 0x3a, 0x04, 0xa8, 0xa6, 0x1f, 0x01, 0x3a, 0x04, 0xa8, 0xa6, 0x1f, 0x01, 0x3a,
	0x04, 0xa8, 0xa6, 0x1f, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x65, 0x73, 0x74, 0x42, 0x10, 0x5a,
	0x0e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pool_pool_with_oneof_proto_rawDescOnce sync.Once
	file_pool_pool_with_oneof_proto_rawDescData = file_pool_pool_with_oneof_proto_rawDesc
)

func file_pool_pool_with_oneof_proto_rawDescGZIP() []byte {
	file_pool_pool_with_oneof_proto_rawDescOnce.Do(func() {
		file_pool_pool_with_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(file_pool_pool_with_oneof_proto_rawDescData)
	})
	return file_pool_pool_with_oneof_proto_rawDescData
}

var file_pool_pool_with_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pool_pool_with_oneof_proto_goTypes = []interface{}{
	(*OneofTest)(nil),                // 0: OneofTest
	(*OneofTest_Test1)(nil),          // 1: OneofTest.Test1
	(*OneofTest_Test2)(nil),          // 2: OneofTest.Test2
	(*OneofTest_Test3)(nil),          // 3: OneofTest.Test3
	(*OneofTest_Test3_Element2)(nil), // 4: OneofTest.Test3.Element2
}
var file_pool_pool_with_oneof_proto_depIdxs = []int32{
	1, // 0: OneofTest.test1:type_name -> OneofTest.Test1
	2, // 1: OneofTest.test2:type_name -> OneofTest.Test2
	3, // 2: OneofTest.test3:type_name -> OneofTest.Test3
	4, // 3: OneofTest.Test3.c:type_name -> OneofTest.Test3.Element2
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pool_pool_with_oneof_proto_init() }
func file_pool_pool_with_oneof_proto_init() {
	if File_pool_pool_with_oneof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pool_pool_with_oneof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneofTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pool_pool_with_oneof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneofTest_Test1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pool_pool_with_oneof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneofTest_Test2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pool_pool_with_oneof_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneofTest_Test3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pool_pool_with_oneof_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneofTest_Test3_Element2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pool_pool_with_oneof_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*OneofTest_Test1_)(nil),
		(*OneofTest_Test2_)(nil),
		(*OneofTest_Test3_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pool_pool_with_oneof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pool_pool_with_oneof_proto_goTypes,
		DependencyIndexes: file_pool_pool_with_oneof_proto_depIdxs,
		MessageInfos:      file_pool_pool_with_oneof_proto_msgTypes,
	}.Build()
	File_pool_pool_with_oneof_proto = out.File
	file_pool_pool_with_oneof_proto_rawDesc = nil
	file_pool_pool_with_oneof_proto_goTypes = nil
	file_pool_pool_with_oneof_proto_depIdxs = nil
}
