// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: slab/nested.proto

package slab

import (
	_ "github.com/planetscale/vtprotobuf/vtproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NestedOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Sequence      *int64                 `protobuf:"varint,2,opt,name=sequence,proto3,oneof" json:"sequence,omitempty"`
	Customer      *NestedParty           `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	Lines         []*NestedLine          `protobuf:"bytes,4,rep,name=lines,proto3" json:"lines,omitempty"`
	Notes         map[string]*NestedNote `protobuf:"bytes,5,rep,name=notes,proto3" json:"notes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Totals        *NestedTotals          `protobuf:"bytes,6,opt,name=totals,proto3" json:"totals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedOrder) Reset() {
	*x = NestedOrder{}
	mi := &file_slab_nested_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedOrder) ProtoMessage() {}

func (x *NestedOrder) ProtoReflect() protoreflect.Message {
	mi := &file_slab_nested_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedOrder.ProtoReflect.Descriptor instead.
func (*NestedOrder) Descriptor() ([]byte, []int) {
	return file_slab_nested_proto_rawDescGZIP(), []int{0}
}

func (x *NestedOrder) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *NestedOrder) GetSequence() int64 {
	if x != nil && x.Sequence != nil {
		return *x.Sequence
	}
	return 0
}

func (x *NestedOrder) GetCustomer() *NestedParty {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *NestedOrder) GetLines() []*NestedLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *NestedOrder) GetNotes() map[string]*NestedNote {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *NestedOrder) GetTotals() *NestedTotals {
	if x != nil {
		return x.Totals
	}
	return nil
}

type NestedParty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TaxId         *string                `protobuf:"bytes,2,opt,name=tax_id,json=taxId,proto3,oneof" json:"tax_id,omitempty"`
	Billing       *NestedAddress         `protobuf:"bytes,3,opt,name=billing,proto3" json:"billing,omitempty"`
	Delivery      *NestedAddress         `protobuf:"bytes,4,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedParty) Reset() {
	*x = NestedParty{}
	mi := &file_slab_nested_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedParty) ProtoMessage() {}

func (x *NestedParty) ProtoReflect() protoreflect.Message {
	mi := &file_slab_nested_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedParty.ProtoReflect.Descriptor instead.
func (*NestedParty) Descriptor() ([]byte, []int) {
	return file_slab_nested_proto_rawDescGZIP(), []int{1}
}

func (x *NestedParty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NestedParty) GetTaxId() string {
	if x != nil && x.TaxId != nil {
		return *x.TaxId
	}
	return ""
}

func (x *NestedParty) GetBilling() *NestedAddress {
	if x != nil {
		return x.Billing
	}
	return nil
}

func (x *NestedParty) GetDelivery() *NestedAddress {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type NestedAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Region        *string                `protobuf:"bytes,3,opt,name=region,proto3,oneof" json:"region,omitempty"`
	Zip           *uint32                `protobuf:"varint,4,opt,name=zip,proto3,oneof" json:"zip,omitempty"`
	Geo           *NestedGeo             `protobuf:"bytes,5,opt,name=geo,proto3" json:"geo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedAddress) Reset() {
	*x = NestedAddress{}
	mi := &file_slab_nested_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedAddress) ProtoMessage() {}

func (x *NestedAddress) ProtoReflect() protoreflect.Message {
	mi := &file_slab_nested_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedAddress.ProtoReflect.Descriptor instead.
func (*NestedAddress) Descriptor() ([]byte, []int) {
	return file_slab_nested_proto_rawDescGZIP(), []int{2}
}

func (x *NestedAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *NestedAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *NestedAddress) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *NestedAddress) GetZip() uint32 {
	if x != nil && x.Zip != nil {
		return *x.Zip
	}
	return 0
}

func (x *NestedAddress) GetGeo() *NestedGeo {
	if x != nil {
		return x.Geo
	}
	return nil
}

type NestedGeo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Accuracy      *float32               `protobuf:"fixed32,3,opt,name=accuracy,proto3,oneof" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedGeo) Reset() {
	*x = NestedGeo{}
	mi := &file_slab_nested_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedGeo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedGeo) ProtoMessage() {}

func (x *NestedGeo) ProtoReflect() protoreflect.Message {
	mi := &file_slab_nested_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedGeo.ProtoReflect.Descriptor instead.
func (*NestedGeo) Descriptor() ([]byte, []int) {
	return file_slab_nested_proto_rawDescGZIP(), []int{3}
}

func (x *NestedGeo) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *NestedGeo) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *NestedGeo) GetAccuracy() float32 {
	if x != nil && x.Accuracy != nil {
		return *x.Accuracy
	}
	return 0
}

type NestedLine struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Sku       string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity  *int64                 `protobuf:"varint,2,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	UnitPrice *float64               `protobuf:"fixed64,3,opt,name=unit_price,json=unitPrice,proto3,oneof" json:"unit_price,omitempty"`
	Product   *NestedProduct         `protobuf:"bytes,4,opt,name=product,proto3" json:"product,omitempty"`
	Discounts []*NestedDiscount      `protobuf:"bytes,5,rep,name=discounts,proto3" json:"discounts,omitempty"`
	// Types that are valid to be assigned to Fulfillment:
	//
	//	*NestedLine_Ship
	//	*NestedLine_PickupLocation
	Fulfillment   isNestedLine_Fulfillment `protobuf_oneof:"fulfillment"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedLine) Reset() {
	*x = NestedLine{}
	mi := &file_slab_nested_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedLine) ProtoMessage() {}

func (x *NestedLine) ProtoReflect() protoreflect.Message {
	mi := &file_slab_nested_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedLine.ProtoReflect.Descriptor instead.
func (*NestedLine) Descriptor() ([]byte, []int) {
	return file_slab_nested_proto_rawDescGZIP(), []int{4}
}

func (x *NestedLine) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *NestedLine) GetQuantity() int64 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *NestedLine) GetUnitPrice() float64 {
	if x != nil && x.UnitPrice != nil {
		return *x.UnitPrice
	}
	return 0
}

func (x *NestedLine) GetProduct() *NestedProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *NestedLine) GetDiscounts() []*NestedDiscount {
	if x != nil {
		return x.Discounts
	}
	return nil
}

func (x *NestedLine) GetFulfillment() isNestedLine_Fulfillment {
	if x != nil {
		return x.Fulfillment
	}
	return nil
}

func (x *NestedLine) GetShip() *NestedShipment {
	if x != nil {
		if x, ok := x.Fulfillment.(*NestedLine_Ship); ok {
			return x.Ship
		}
	}
	return nil
}

func (x *NestedLine) GetPickupLocation() string {
	if x != nil {
		if x, ok := x.Fulfillment.(*NestedLine_PickupLocation); ok {
			return x.PickupLocation
		}
	}
	return ""
}

type isNestedLine_Fulfillment interface {
	isNestedLine_Fulfillment()
}

type NestedLine_Ship struct {
	Ship *NestedShipment `protobuf:"bytes,6,opt,name=ship,proto3,oneof"`
}

type NestedLine_PickupLocation struct {
	PickupLocation string `protobuf:"bytes,7,opt,name=pickup_location,json=pickupLocation,proto3,oneof"`
}

func (*NestedLine_Ship) isNestedLine_Fulfillment() {}

func (*NestedLine_PickupLocation) isNestedLine_Fulfillment() {}

type NestedProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Thumbnail     []byte                 `protobuf:"bytes,2,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Dims          *NestedDimensions      `protobuf:"bytes,4,opt,name=dims,proto3" json:"dims,omitempty"`
	Brand         *string                `protobuf:"bytes,5,opt,name=brand,proto3,oneof" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedProduct) Reset() {
	*x = NestedProduct{}
	mi := &file_slab_nested_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedProduct) ProtoMessage() {}

func (x *NestedProduct) ProtoReflect() protoreflect.Message {
	mi := &file_slab_nested_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedProduct.ProtoReflect.Descriptor instead.
func (*NestedProduct) Descriptor() ([]byte, []int) {
	return file_slab_nested_proto_rawDescGZIP(), []int{5}
}

func (x *NestedProduct) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NestedProduct) GetThumbnail() []byte {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

func (x *NestedProduct) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *NestedProduct) GetDims() *NestedDimensions {
	if x != nil {
		return x.Dims
	}
	return nil
}

func (x *NestedProduct) GetBrand() string {
	if x != nil && x.Brand != nil {
		return *x.Brand
	}
	return ""
}

type NestedDimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         *float64               `protobuf:"fixed64,1,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height        *float64               `protobuf:"fixed64,2,opt,name=height,proto3,oneof" json:"height,omitempty"`
	Depth         *float64               `protobuf:"fixed64,3,opt,name=depth,proto3,oneof" json:"depth,omitempty"`
	WeightMg      *uint64                `protobuf:"varint,4,opt,name=weight_mg,json=weightMg,proto3,oneof" json:"weight_mg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedDimensions) Reset() {
	*x = NestedDimensions{}
	mi := &file_slab_nested_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedDimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedDimensions) ProtoMessage() {}

func (x *NestedDimensions) ProtoReflect() protoreflect.Message {
	mi := &file_slab_nested_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedDimensions.ProtoReflect.Descriptor instead.
func (*NestedDimensions) Descriptor() ([]byte, []int) {
	return file_slab_nested_proto_rawDescGZIP(), []int{6}
}

func (x *NestedDimensions) GetWidth() float64 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *NestedDimensions) GetHeight() float64 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *NestedDimensions) GetDepth() float64 {
	if x != nil && x.Depth != nil {
		return *x.Depth
	}
	return 0
}

func (x *NestedDimensions) GetWeightMg() uint64 {
	if x != nil && x.WeightMg != nil {
		return *x.WeightMg
	}
	return 0
}

type NestedDiscount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	AmountMicros  *int64                 `protobuf:"zigzag64,2,opt,name=amount_micros,json=amountMicros,proto3,oneof" json:"amount_micros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedDiscount) Reset() {
	*x = NestedDiscount{}
	mi := &file_slab_nested_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedDiscount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedDiscount) ProtoMessage() {}

func (x *NestedDiscount) ProtoReflect() protoreflect.Message {
	mi := &file_slab_nested_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedDiscount.ProtoReflect.Descriptor instead.
func (*NestedDiscount) Descriptor() ([]byte, []int) {
	return file_slab_nested_proto_rawDescGZIP(), []int{7}
}

func (x *NestedDiscount) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NestedDiscount) GetAmountMicros() int64 {
	if x != nil && x.AmountMicros != nil {
		return *x.AmountMicros
	}
	return 0
}

type NestedShipment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Carrier       string                 `protobuf:"bytes,1,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Destination   *NestedAddress         `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	EtaUnix       *uint64                `protobuf:"fixed64,3,opt,name=eta_unix,json=etaUnix,proto3,oneof" json:"eta_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedShipment) Reset() {
	*x = NestedShipment{}
	mi := &file_slab_nested_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedShipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedShipment) ProtoMessage() {}

func (x *NestedShipment) ProtoReflect() protoreflect.Message {
	mi := &file_slab_nested_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedShipment.ProtoReflect.Descriptor instead.
func (*NestedShipment) Descriptor() ([]byte, []int) {
	return file_slab_nested_proto_rawDescGZIP(), []int{8}
}

func (x *NestedShipment) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *NestedShipment) GetDestination() *NestedAddress {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *NestedShipment) GetEtaUnix() uint64 {
	if x != nil && x.EtaUnix != nil {
		return *x.EtaUnix
	}
	return 0
}

type NestedNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,3,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedNote) Reset() {
	*x = NestedNote{}
	mi := &file_slab_nested_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedNote) ProtoMessage() {}

func (x *NestedNote) ProtoReflect() protoreflect.Message {
	mi := &file_slab_nested_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedNote.ProtoReflect.Descriptor instead.
func (*NestedNote) Descriptor() ([]byte, []int) {
	return file_slab_nested_proto_rawDescGZIP(), []int{9}
}

func (x *NestedNote) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *NestedNote) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NestedNote) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type NestedTotals struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubtotalMicros *int64                 `protobuf:"varint,1,opt,name=subtotal_micros,json=subtotalMicros,proto3,oneof" json:"subtotal_micros,omitempty"`
	TaxMicros      *int64                 `protobuf:"varint,2,opt,name=tax_micros,json=taxMicros,proto3,oneof" json:"tax_micros,omitempty"`
	TotalMicros    *int64                 `protobuf:"varint,3,opt,name=total_micros,json=totalMicros,proto3,oneof" json:"total_micros,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NestedTotals) Reset() {
	*x = NestedTotals{}
	mi := &file_slab_nested_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedTotals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedTotals) ProtoMessage() {}

func (x *NestedTotals) ProtoReflect() protoreflect.Message {
	mi := &file_slab_nested_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedTotals.ProtoReflect.Descriptor instead.
func (*NestedTotals) Descriptor() ([]byte, []int) {
	return file_slab_nested_proto_rawDescGZIP(), []int{10}
}

func (x *NestedTotals) GetSubtotalMicros() int64 {
	if x != nil && x.SubtotalMicros != nil {
		return *x.SubtotalMicros
	}
	return 0
}

func (x *NestedTotals) GetTaxMicros() int64 {
	if x != nil && x.TaxMicros != nil {
		return *x.TaxMicros
	}
	return 0
}

func (x *NestedTotals) GetTotalMicros() int64 {
	if x != nil && x.TotalMicros != nil {
		return *x.TotalMicros
	}
	return 0
}

var File_slab_nested_proto protoreflect.FileDescriptor

const file_slab_nested_proto_rawDesc = "" +
	"\n" +
	"\x11slab/nested.proto\x1a3github.com/planetscale/vtprotobuf/vtproto/ext.proto\"\xc6\x02\n" +
	"\vNestedOrder\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\bsequence\x18\x02 \x01(\x03H\x00R\bsequence\x88\x01\x01\x12(\n" +
	"\bcustomer\x18\x03 \x01(\v2\f.NestedPartyR\bcustomer\x12!\n" +
	"\x05lines\x18\x04 \x03(\v2\v.NestedLineR\x05lines\x12-\n" +
	"\x05notes\x18\x05 \x03(\v2\x17.NestedOrder.NotesEntryR\x05notes\x12%\n" +
	"\x06totals\x18\x06 \x01(\v2\r.NestedTotalsR\x06totals\x1aE\n" +
	"\n" +
	"NotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.NestedNoteR\x05value:\x028\x01:\x04\xb8\xa6\x1f\x01B\v\n" +
	"\t_sequence\"\x9e\x01\n" +
	"\vNestedParty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\x06tax_id\x18\x02 \x01(\tH\x00R\x05taxId\x88\x01\x01\x12(\n" +
	"\abilling\x18\x03 \x01(\v2\x0e.NestedAddressR\abilling\x12*\n" +
	"\bdelivery\x18\x04 \x01(\v2\x0e.NestedAddressR\bdeliveryB\t\n" +
	"\a_tax_id\"\xa0\x01\n" +
	"\rNestedAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x1b\n" +
	"\x06region\x18\x03 \x01(\tH\x00R\x06region\x88\x01\x01\x12\x15\n" +
	"\x03zip\x18\x04 \x01(\rH\x01R\x03zip\x88\x01\x01\x12\x1c\n" +
	"\x03geo\x18\x05 \x01(\v2\n" +
	".NestedGeoR\x03geoB\t\n" +
	"\a_regionB\x06\n" +
	"\x04_zip\"]\n" +
	"\tNestedGeo\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x1f\n" +
	"\baccuracy\x18\x03 \x01(\x02H\x00R\baccuracy\x88\x01\x01B\v\n" +
	"\t_accuracy\"\xb9\x02\n" +
	"\n" +
	"NestedLine\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1f\n" +
	"\bquantity\x18\x02 \x01(\x03H\x01R\bquantity\x88\x01\x01\x12\"\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\x01H\x02R\tunitPrice\x88\x01\x01\x12(\n" +
	"\aproduct\x18\x04 \x01(\v2\x0e.NestedProductR\aproduct\x12-\n" +
	"\tdiscounts\x18\x05 \x03(\v2\x0f.NestedDiscountR\tdiscounts\x12%\n" +
	"\x04ship\x18\x06 \x01(\v2\x0f.NestedShipmentH\x00R\x04ship\x12)\n" +
	"\x0fpickup_location\x18\a \x01(\tH\x00R\x0epickupLocationB\r\n" +
	"\vfulfillmentB\v\n" +
	"\t_quantityB\r\n" +
	"\v_unit_price\"\x8e\x02\n" +
	"\rNestedProduct\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1c\n" +
	"\tthumbnail\x18\x02 \x01(\fR\tthumbnail\x12>\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x1e.NestedProduct.AttributesEntryR\n" +
	"attributes\x12%\n" +
	"\x04dims\x18\x04 \x01(\v2\x11.NestedDimensionsR\x04dims\x12\x19\n" +
	"\x05brand\x18\x05 \x01(\tH\x00R\x05brand\x88\x01\x01\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_brand\"\xb4\x01\n" +
	"\x10NestedDimensions\x12\x19\n" +
	"\x05width\x18\x01 \x01(\x01H\x00R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\x02 \x01(\x01H\x01R\x06height\x88\x01\x01\x12\x19\n" +
	"\x05depth\x18\x03 \x01(\x01H\x02R\x05depth\x88\x01\x01\x12 \n" +
	"\tweight_mg\x18\x04 \x01(\x04H\x03R\bweightMg\x88\x01\x01B\b\n" +
	"\x06_widthB\t\n" +
	"\a_heightB\b\n" +
	"\x06_depthB\f\n" +
	"\n" +
	"_weight_mg\"`\n" +
	"\x0eNestedDiscount\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12(\n" +
	"\ramount_micros\x18\x02 \x01(\x12H\x00R\famountMicros\x88\x01\x01B\x10\n" +
	"\x0e_amount_micros\"\x89\x01\n" +
	"\x0eNestedShipment\x12\x18\n" +
	"\acarrier\x18\x01 \x01(\tR\acarrier\x120\n" +
	"\vdestination\x18\x02 \x01(\v2\x0e.NestedAddressR\vdestination\x12\x1e\n" +
	"\beta_unix\x18\x03 \x01(\x06H\x00R\aetaUnix\x88\x01\x01B\v\n" +
	"\t_eta_unix\"i\n" +
	"\n" +
	"NestedNote\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12!\n" +
	"\ttimestamp\x18\x03 \x01(\x03H\x00R\ttimestamp\x88\x01\x01B\f\n" +
	"\n" +
	"_timestamp\"\xbc\x01\n" +
	"\fNestedTotals\x12,\n" +
	"\x0fsubtotal_micros\x18\x01 \x01(\x03H\x00R\x0esubtotalMicros\x88\x01\x01\x12\"\n" +
	"\n" +
	"tax_micros\x18\x02 \x01(\x03H\x01R\ttaxMicros\x88\x01\x01\x12&\n" +
	"\ftotal_micros\x18\x03 \x01(\x03H\x02R\vtotalMicros\x88\x01\x01B\x12\n" +
	"\x10_subtotal_microsB\r\n" +
	"\v_tax_microsB\x0f\n" +
	"\r_total_microsB\x10Z\x0etestproto/slabb\x06proto3"

var (
	file_slab_nested_proto_rawDescOnce sync.Once
	file_slab_nested_proto_rawDescData []byte
)

func file_slab_nested_proto_rawDescGZIP() []byte {
	file_slab_nested_proto_rawDescOnce.Do(func() {
		file_slab_nested_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slab_nested_proto_rawDesc), len(file_slab_nested_proto_rawDesc)))
	})
	return file_slab_nested_proto_rawDescData
}

var file_slab_nested_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_slab_nested_proto_goTypes = []any{
	(*NestedOrder)(nil),      // 0: NestedOrder
	(*NestedParty)(nil),      // 1: NestedParty
	(*NestedAddress)(nil),    // 2: NestedAddress
	(*NestedGeo)(nil),        // 3: NestedGeo
	(*NestedLine)(nil),       // 4: NestedLine
	(*NestedProduct)(nil),    // 5: NestedProduct
	(*NestedDimensions)(nil), // 6: NestedDimensions
	(*NestedDiscount)(nil),   // 7: NestedDiscount
	(*NestedShipment)(nil),   // 8: NestedShipment
	(*NestedNote)(nil),       // 9: NestedNote
	(*NestedTotals)(nil),     // 10: NestedTotals
	nil,                      // 11: NestedOrder.NotesEntry
	nil,                      // 12: NestedProduct.AttributesEntry
}
var file_slab_nested_proto_depIdxs = []int32{
	1,  // 0: NestedOrder.customer:type_name -> NestedParty
	4,  // 1: NestedOrder.lines:type_name -> NestedLine
	11, // 2: NestedOrder.notes:type_name -> NestedOrder.NotesEntry
	10, // 3: NestedOrder.totals:type_name -> NestedTotals
	2,  // 4: NestedParty.billing:type_name -> NestedAddress
	2,  // 5: NestedParty.delivery:type_name -> NestedAddress
	3,  // 6: NestedAddress.geo:type_name -> NestedGeo
	5,  // 7: NestedLine.product:type_name -> NestedProduct
	7,  // 8: NestedLine.discounts:type_name -> NestedDiscount
	8,  // 9: NestedLine.ship:type_name -> NestedShipment
	12, // 10: NestedProduct.attributes:type_name -> NestedProduct.AttributesEntry
	6,  // 11: NestedProduct.dims:type_name -> NestedDimensions
	2,  // 12: NestedShipment.destination:type_name -> NestedAddress
	9,  // 13: NestedOrder.NotesEntry.value:type_name -> NestedNote
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_slab_nested_proto_init() }
func file_slab_nested_proto_init() {
	if File_slab_nested_proto != nil {
		return
	}
	file_slab_nested_proto_msgTypes[0].OneofWrappers = []any{}
	file_slab_nested_proto_msgTypes[1].OneofWrappers = []any{}
	file_slab_nested_proto_msgTypes[2].OneofWrappers = []any{}
	file_slab_nested_proto_msgTypes[3].OneofWrappers = []any{}
	file_slab_nested_proto_msgTypes[4].OneofWrappers = []any{
		(*NestedLine_Ship)(nil),
		(*NestedLine_PickupLocation)(nil),
	}
	file_slab_nested_proto_msgTypes[5].OneofWrappers = []any{}
	file_slab_nested_proto_msgTypes[6].OneofWrappers = []any{}
	file_slab_nested_proto_msgTypes[7].OneofWrappers = []any{}
	file_slab_nested_proto_msgTypes[8].OneofWrappers = []any{}
	file_slab_nested_proto_msgTypes[9].OneofWrappers = []any{}
	file_slab_nested_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slab_nested_proto_rawDesc), len(file_slab_nested_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slab_nested_proto_goTypes,
		DependencyIndexes: file_slab_nested_proto_depIdxs,
		MessageInfos:      file_slab_nested_proto_msgTypes,
	}.Build()
	File_slab_nested_proto = out.File
	file_slab_nested_proto_goTypes = nil
	file_slab_nested_proto_depIdxs = nil
}
