// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: testproto/grpc/inner/inner.proto

package inner

import (
	_ "github.com/planetscale/vtprotobuf/vtproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessageRequest) Reset() {
	*x = TestMessageRequest{}
	mi := &file_testproto_grpc_inner_inner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessageRequest) ProtoMessage() {}

func (x *TestMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_grpc_inner_inner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessageRequest.ProtoReflect.Descriptor instead.
func (*TestMessageRequest) Descriptor() ([]byte, []int) {
	return file_testproto_grpc_inner_inner_proto_rawDescGZIP(), []int{0}
}

type TestMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessageResponse) Reset() {
	*x = TestMessageResponse{}
	mi := &file_testproto_grpc_inner_inner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessageResponse) ProtoMessage() {}

func (x *TestMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_grpc_inner_inner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessageResponse.ProtoReflect.Descriptor instead.
func (*TestMessageResponse) Descriptor() ([]byte, []int) {
	return file_testproto_grpc_inner_inner_proto_rawDescGZIP(), []int{1}
}

var File_testproto_grpc_inner_inner_proto protoreflect.FileDescriptor

const file_testproto_grpc_inner_inner_proto_rawDesc = "" +
	"\n" +
	" testproto/grpc/inner/inner.proto\x12\x05inner\x1a3github.com/planetscale/vtprotobuf/vtproto/ext.proto\"\x1a\n" +
	"\x12TestMessageRequest:\x04\xa8\xa6\x1f\x01\"\x1b\n" +
	"\x13TestMessageResponse:\x04\xa8\xa6\x1f\x01B\x16Z\x14testproto/grpc/innerb\x06proto3"

var (
	file_testproto_grpc_inner_inner_proto_rawDescOnce sync.Once
	file_testproto_grpc_inner_inner_proto_rawDescData []byte
)

func file_testproto_grpc_inner_inner_proto_rawDescGZIP() []byte {
	file_testproto_grpc_inner_inner_proto_rawDescOnce.Do(func() {
		file_testproto_grpc_inner_inner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testproto_grpc_inner_inner_proto_rawDesc), len(file_testproto_grpc_inner_inner_proto_rawDesc)))
	})
	return file_testproto_grpc_inner_inner_proto_rawDescData
}

var file_testproto_grpc_inner_inner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testproto_grpc_inner_inner_proto_goTypes = []any{
	(*TestMessageRequest)(nil),  // 0: inner.TestMessageRequest
	(*TestMessageResponse)(nil), // 1: inner.TestMessageResponse
}
var file_testproto_grpc_inner_inner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testproto_grpc_inner_inner_proto_init() }
func file_testproto_grpc_inner_inner_proto_init() {
	if File_testproto_grpc_inner_inner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testproto_grpc_inner_inner_proto_rawDesc), len(file_testproto_grpc_inner_inner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testproto_grpc_inner_inner_proto_goTypes,
		DependencyIndexes: file_testproto_grpc_inner_inner_proto_depIdxs,
		MessageInfos:      file_testproto_grpc_inner_inner_proto_msgTypes,
	}.Build()
	File_testproto_grpc_inner_inner_proto = out.File
	file_testproto_grpc_inner_inner_proto_goTypes = nil
	file_testproto_grpc_inner_inner_proto_depIdxs = nil
}
